### ISSUE TITLE
Instead of color coding an asset by the marketplace it's hosted on; come up with a more user-friendly alternative

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/design-system#11]
## Scope

- See that e.g. OCEAN data sets, we color pink
- Big data protocol data sets, we color green.

<img width="598" alt="Screen Shot 2021-11-08 at 15 34 19" src="https://user-images.githubusercontent.com/2758453/140760767-9f41c42a-758d-454e-a5af-1acf2c188c73.png">

- From our UX designer, we got the following feedback:

<img width="523" alt="Screen Shot 2021-11-08 at 15 35 39" src="https://user-images.githubusercontent.com/2758453/140760981-e2617e02-3116-49d5-ad99-9437739b78a5.png">

## Deliverable

- Make information on where the data set was published available in a different way but color-coding the data asset in the table
- Options can be:
  - show the marketplace's icon next to the link
  - show text "ocean protocol" somewhere
  - Add a tag label

## Time estimate

- Discussion here on GitHub is included in the total working time
- A simple proposal can take up to 4 hours of time.

**Comment by il3ven** [comment]
Up till now I didn't know that we had big data protocol sets. In my opinion we should show an icon for making the data sets.

![image](https://user-images.githubusercontent.com/4337699/141183114-938bdce4-1d8a-4189-8503-b8bd59dce2e7.png)

> I tried a few things and this looks the best
