### ISSUE TITLE
create a card component for signing up to the RPI newsletter

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/design-system#20]
## Scope

- A goal of RPI is to start a newsletter. We're gonna use https://buttondown.email/
- For that, we'll have to have some UI component that matches the rugpullindex.com design language
- It's the second time that I've built a newsletter component. The first one can still be seen over at: https://doctoverse.com/
- I think we want to go for a similar arrangement of visual components

<img width="575" alt="Screen Shot 2021-11-16 at 17 06 43" src="https://user-images.githubusercontent.com/2758453/142021581-a265650c-af19-4253-98c6-0741f8ebb3e2.png">

## Deliverables

- Using classless.de definition and potentially custom CSS, come up with a newsletter UI element that we can embed on e.g. our front page
- Integrating with buttondown.email isn't a requirement. I can do that later
- Component should work well on mobile, tablets and desktop. The input element should be designed such that there's enough space for a user to hit the clicks
- A "success" animation isn't required as we'll redirect to a sub-page of buttondown.email

## time estimate

- 2-4h

**Comment by il3ven** [comment]
Closed via #33
