### ISSUE TITLE
For a link with attribute target="_blank", add ::after pseudoelement with "↗" as content 

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/design-system#22]
## Scope

- For our users, we want to indicate which links lead to external pages and which links lead to internal pages
- For that, many sites add this symbol "↗" as an indicator to a link
- Using CSS, we can target all `<a>` tags that have the attribute target="_blank" and add a pseudoelement ::after

## Deliverables

- Add the ::after pseudoelement for any type of link leading to external sites and send a PR

## Time estimate

- 1h

**Comment by Joaos98** [comment]
Hello, I've submitted a PR that should close this issue.
