### ISSUE TITLE
Design data asset profile page

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/design-system#24]
## Scope

- Old design by Scott

<img width="631" alt="Screen Shot 2021-11-21 at 17 56 37" src="https://user-images.githubusercontent.com/2758453/142771520-2a95c85a-b441-4c9c-9552-4f4593888719.png">

- Right now, rugpullindex doesn't have a profile page for an asset as e.g. coingecko or coinmarketcap has them e.g. https://www.coingecko.com/en/coins/ocean-protocol
- But we often get requests that our assets should have a page with more detailed information, and I also think that the mental model to understand our product offering would be better did we have a detailed view.
- - Given our latest understanding of the product, how should an data asset profile page look like. What is the information that our users are craving for?

## Deliverable

- This task is primarily for a dev + a designer; We want to have a visual design
- and then additionally, we want to implement this design here as a CSS mockup that can later be hydrated using the RPI backend data

## time estimate

- beyond 4h

**Comment by il3ven** [comment]
I also recommend that this page should be opened by clicking on the data token's address.

**Comment by Taschmahal** [comment]
See rough proposal here: https://www.figma.com/file/QOuiOjuPtWFpy6NtnTzuRd/Rug-Pull-Index?node-id=5%3A3188

**Comment by TimDaub** [comment]
@florianmodel thanks for the mockups. They look great. I'll now consider this issue "done". Over the course of the next few weeks, we should now extract issues from your figma design and implement them ticket by ticket until we get close to your design. Thanks.
