### ISSUE TITLE
Remove test.html

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/design-system#30]
# Scope

- test.html isn't useful anymore, we now use the script in index.js for retrieving the HTML part

## deliverables

- remove test.html

# time estimate

this task is too small for any payment.

**Comment by rahulchandra17** [comment]
I have deleted please merge my pull request

**Comment by TimDaub** [comment]
Fixed in #31 

> I have deleted please merge my pull request

Not sure what you're referring to. Did you also send a PR? I can't see it...
