### ISSUE TITLE
some OS doesn't include Garamond font

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/design-system#9]
## Context

- we use the "Garamond" font face
- on Mac OS where Garamond is included as a font by default, the website looks like this:

<img width="1149" alt="Screen Shot 2021-10-28 at 15 24 31" src="https://user-images.githubusercontent.com/2758453/139264621-cb086187-c581-4c47-a78b-bb570b14a3b6.png">

where as on Windows 10/11, the Garamond font face doesn't seem to be embedded by default

![image](https://user-images.githubusercontent.com/2758453/139264299-59ac8d68-f919-4f7e-be45-f8d8b5068553.png)

## Deliverables

- Find websafe font that can be used instead of Garamond when its not available
- Implement backup font in design.css

## Time estimate

- 1-2h

**Comment by il3ven** [comment]
After trying 3 different versions of chrome, two OS and 3 machines. I have been able to replicate it.

The problem is not due to different chrome version nor OS. I found a Windows machine where this was replicable.

The reason - on some machines, Windows include the Garamond font but that font is not the same as Mac. The Windows Garamond font is a serif font.

![image](https://user-images.githubusercontent.com/4337699/139529319-dba7779a-fe2c-44a5-9d18-19b7378f5f5d.png)

Here is also an [office link](https://1drv.ms/w/s!AgBKND2E6WAskyOZAIQ6neVA5uiH?e=FTaeJ4) showing the font.

The solution can be to replace Garamond with some other safer font or import a font from a URL.

**Comment by il3ven** [comment]
> The solution can be to replace Garamond with some other safer font or import a font from a URL.

@TimDaub Shall I create a PR?

**Comment by TimDaub** [comment]
> The solution can be to replace Garamond with some other safer font or import a font from a URL.

Maybe... What's the most-similar looking, sans-serif, web-safe font to Garamond?

**Comment by il3ven** [comment]
What about Arial? My computer currently falls back to Arial and the screenshots you share look similar to what I see here.

![image](https://user-images.githubusercontent.com/4337699/140179192-7642a6df-9d78-48ef-9dac-a99865a76f16.png)

> Website using Arial font

**Comment by TimDaub** [comment]
Not sure. I kinda wanna have Garamond. I'm asking StackOverflow for help: https://stackoverflow.com/questions/69839934/font-family-garamond-sans-serif-wont-always-produce-sans-serif-font-face-wh

**Comment by TimDaub** [comment]
You know what could also be is that the system doesn't find a sans-serif version of Garamond and hence just switches to the next best default font (on Mac OS it's Helvetica).
Maybe Garamond doesn't have a sans-serif type face: 
![image](https://user-images.githubusercontent.com/2758453/140321707-69e7cb49-2d9d-4e1c-bfac-e3471f666562.png)

Check this out:

![helvetika](https://user-images.githubusercontent.com/2758453/140321504-021e407f-0eac-480c-bc7d-755b351aae64.gif)

**Comment by il3ven** [comment]
This is really interesting. Your mac doesn't have Garamond and is falling back to Helvetica. After a quick search I think the Garamond is a serif font.

I see two options
- Use Arial as the default font. I still think it looks quite similar.
- Import a font similar Helvetica using `font-face`.

**Comment by TimDaub** [comment]
I suggest the following: We use "Helvetica" as default and we fall back to "Arial". That can be a PR.

**Comment by il3ven** [comment]
> I suggest the following: We use "Helvetica" as default and we fall back to "Arial". That can be a PR.

Seems like the best solution. Let me make a PR.
